### ISSUE TITLE
Does not log anything starting at commit fff9d1d using --output flag

### ISSUE THREAD

**Issue by theryangeary** [kernc/logkeys#205]
git bisect and testing shows that this commit introduces this issue:
```
fff9d1d60f85a09208935170940c14ef7604b9d0 is the first bad commit
commit fff9d1d60f85a09208935170940c14ef7604b9d0
Author: Thomas Weber <thomas.weber@notengrafik.com>
Date:   Fri Sep 20 22:40:48 2019 +0200

    Make main loop a function of its own

 src/logkeys.cc | 171 +++++++++++++++++++++++++++++++--------------------------
 1 file changed, 92 insertions(+), 79 deletions(-)
```
It seems from an external standpoint that it simply isn't writing to the log file whatsoever. I'm running as `sudo logkeys -s -o keys.log` on Arch: `Linux commodus 5.3.5-arch1-1-ARCH #1 SMP PREEMPT Mon Oct 7 19:03:08 UTC 2019 x86_64 GNU/Linux`

**Comment by theryangeary** [comment]
- It is not writing to the file at all.
- `log_event()` is being called.
- I do not have multiple keyboards connected, only the laptop's built in keyboard

**Comment by theryangeary** [comment]
Found it! It appears as though the file is being opened with a relative path (i.e. if I say `-o keys.log` it will put it in the CWD of the process) but the process CWD appears to actually be the root directory `/`, so it ends up writing it to `/keys.log` when I was expecting it to be in `$PWD/keys.log`.

**Comment by kernc** [comment]
The culprit is [`daemon(3)`](http://man7.org/linux/man-pages/man3/daemon.3.html) call, which is passed `nochdir=0` and which since fff9d1d60f85a09208935170940c14ef7604b9d0 happens before the log file is opened.
https://github.com/kernc/logkeys/blob/2e33f93efdf11bafee26a987355c82ce913a41c3/src/logkeys.cc#L705

The simple options I see, not in preferential order:
* Open the file before daemonization; pass the file descriptor to `log_loop()`.
* Call `daemon(nochdir=1)`.
* Resolve `args.logfile` to absolute path before daemonization.
